### ISSUE TITLE
Request for prune

### ISSUE THREAD

**Issue by natros** [JChrist/gitextender#1]
I believe one feature is missing that is present in IntelliJ that is prune the branches that no longer exist.
From command line I use `git remote prune origin` and IntelliJ uses 
`git -c core.quotepath=false fetch origin --progress --prune`

Thank you for this awesome plugin.

**Comment by JChrist** [comment]
Right now the plugin is fetching and pruning only the tracked remotes, the ones that have a local counter-part. I will be checking out your suggestion, as well as any consequence it might have, i.e does it fetch all remote branches, no matter if they are checked out locally or not?

I would be extremely happy if this plugin helped you in the slightest!

**Comment by JChrist** [comment]
This was added in the latest version 0.1.2, using GitFetcher of Git4Idea
