### ISSUE TITLE
Missing loading spinner, potentially infinite fetching, locked Tools menu item

### ISSUE THREAD

**Issue by lppedd** [JChrist/gitextender#16]
I've noticed three issues fiddling with the plugin after #13 

1. The loading spinner is no more there
2. Keeping ALT+T pressed cause infinite (well, after a while it stops luckily) fetching and rebasing
3. The ALT+T keybinding interfere with the Tools menu item shortcut and somehow disables it
![image](https://user-images.githubusercontent.com/19871649/65633439-6b72de00-dfdc-11e9-9890-486d4dd321e5.png)

**Comment by JChrist** [comment]
Hi!
I believe all these issues are related to dropping `Task.Backgroundable`  for `BackgroundableRepoUpdateTask`. This was the way to show the spinner (and somehow, not really sure, make the task appear as running).
However, many tests (manual and integration) resulted in a deadlock with it.
I will need some time to bring it back, as it's less than _easy_ to debug it.

**Comment by JChrist** [comment]
this should be addressed in version 0.5.2, uploaded after merging #17

**Comment by lppedd** [comment]
> I will need some time to bring it back

Well that was some *fast* time hahaha
Thanks, and I can confirm everything seems to work as expected now.
I will let you know about the `Tools` menu as soon as I'm on my Windows 10 machine again.
On Debian Linux everything is ok.

**Comment by JChrist** [comment]
Well, you know how that goes...
If it's fast and working, it won't be pretty... It will need proper re-writing at some point, but I prefer for 2019.3 to be released first, as it contains several deprecations that need to be addressed, as well.
