### ISSUE TITLE
com.intellij.diagnostic.PluginException: No display name is specified for configurable gr.jchrist.gitextender.configuration.SettingsView in xml file

### ISSUE THREAD

**Issue by PrOF-kk** [JChrist/gitextender#70]
`specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened [Plugin: gr.jchrist.gitextender]`

On PhpStorm 2023.2 (new UI), I don't think it used to happen on 2023.1.* but I'm not 100% sure.

**Comment by JTI-ORGADATA** [comment]
Also on WebStorm 2023.2.3 🧑‍🔧

**Comment by umputun** [comment]
same on Goland, 2023.3.1
